index.html
style.css

Cf. https://github.com/koreader/koreader/issues/4904

Add some screenshots

---

gallery.html
generate-gallery.py
index.html

References <https://github.com/koreader/koreader/issues/8229#issuecomment-995804833>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader.github.io/13)

Add logo gallery

---

style.css

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader.github.io/10)

Add linear-gradient background

---

index.html

See <https://github.com/koreader/koreader/issues/8058#issuecomment-1412656013>.

Change the userguide filename back to one that's generic

---

user_guide/index.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader.github.io/23)

Fix last update date

---

index.html

See https://github.com/koreader/koreader.github.io/pull/23#issuecomment-1759445399
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader.github.io/24)

Update user guide link to new HTML page

---

gallery.html

Fixes #26.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader.github.io/27)

Add the last year of logos to logo gallery

---

user_guide/index.html

Fixes #25.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader.github.io/28)

Add break-before: always to user guide main chapter headings

---

.github/workflows/manual-epub.yml

(just testing quickly)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader.github.io/29)

Automatically generate EPUB artifact

---

user_guide/index.html

Small update to the CSS so that the site is viewable on mobile phones without scrolling.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader.github.io/31)

Remove horizontal scroll on small screens

---

CONTRIBUTING.md

See <https://github.com/koreader/koreader.github.io/pull/32#issuecomment-1834267034>.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader.github.io/34)

Add a basic CONTRIBUTING.md

---

.github/workflows/manual-preview.yml

Cf. <https://github.com/koreader/koreader.github.io/pull/31#discussion_r1409965946>
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader.github.io/33)

GitHub Actions: add manual HTML preview

---

user_guide/index.html

A good idea in general, but required for Weblate. See <https://github.com/koreader/koreader/issues/11147#issuecomment-1837152321>.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader.github.io/37)

User guide: ensure valid HTML

---

.github/workflows/check.yml
user_guide/en.html

See #44.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader.github.io/45)

[CI] Add html2po syntax check

---

user_guide/en.html

Changelog is here: https://github.com/koreader/koreader/issues/11147#issuecomment-1988165418
If there is a problem, just tell me Frenzie. I will fix it.
I added title and lang elements so weblate translators should change these accordingly. Probably they will notice.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader.github.io/46)

24.03 Update

---

user_guide/en.html

In reply to https://github.com/koreader/koreader/issues/11147#issuecomment-2122655326
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader.github.io/50)

User guide: set dir="ltr" on <html> so it can be translated

---

.github/workflows/manual-preview.yml

Overlooked when renaming from index.html to en.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader.github.io/51)

User guide: fix preview, add RTL preview

---

user_guide/en.html

This will come out better in crengine.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader.github.io/52)

User guide: change max-width to 80ch

---

.github/workflows/manual-epub.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader.github.io/53)

manual-epub.yml: update upload-artifact action

---

.github/workflows/manual-preview.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader.github.io/56)

manual-preview.yml: update html-preview-action

---

i18n/po/ca.po
i18n/po/cs.po
i18n/po/de.po
i18n/po/el.po
i18n/po/en.po
i18n/po/es.po
i18n/po/fa.po
i18n/po/fi.po
i18n/po/fr.po
i18n/po/gl.po
i18n/po/hu.po
i18n/po/ia.po
i18n/po/ja.po
i18n/po/ko.po
i18n/po/nl.po
i18n/po/pt_BR.po
i18n/po/pt_PT.po
i18n/po/ro_MD.po
i18n/po/ru.po
i18n/po/sk.po
i18n/po/sr.po
i18n/po/ta.po
i18n/po/th.po
i18n/po/uk.po
i18n/po/user_guide.pot
i18n/po/vi.po
i18n/po/zh_Hans.po
i18n/user_guide.pot

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader.github.io/63)

Fix PO file syntax

---

i18n/po/ca.po
i18n/po/cs.po
i18n/po/de.po
i18n/po/el.po
i18n/po/en.po
i18n/po/es.po
i18n/po/fa.po
i18n/po/fi.po
i18n/po/fr.po
i18n/po/gl.po
i18n/po/hu.po
i18n/po/ia.po
i18n/po/ja.po
i18n/po/ko.po
i18n/po/nl.po
i18n/po/pt_BR.po
i18n/po/pt_PT.po
i18n/po/ro_MD.po
i18n/po/ru.po
i18n/po/sk.po
i18n/po/sr.po
i18n/po/ta.po
i18n/po/th.po
i18n/po/uk.po
i18n/po/user_guide.pot
i18n/po/vi.po
i18n/po/zh_Hans.po
i18n/user_guide.pot

Reverts koreader/koreader.github.io#63
The syntax was fine, just Weblate wasn't…
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader.github.io/64)

Revert "Fix PO file syntax"

---

i18n/po/nl.po

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader.github.io/66)

Translate Dutch up to line 455

---

i18n/po/nl.po

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader.github.io/67)

Translate more Dutch

---

i18n/po/nl.po

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader.github.io/68)

Translate some more Dutch

---

.github/workflows/translation-update.yml

Supersedes #75.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader.github.io/76)

[i18n, CI] Add automated picture src replacement

---

user_guide/en.html

See #80.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader.github.io/81)

Add translation warning to user guide HTML
